<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TabelMasterKasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tabel_master_kas')->insert([
            [
                'gl_arus_kas' => '001-11000',
                'line' => 'HEADING',
                'code_arus_kas' => '11000',
                'nama_arus_kas' => 'KEGIATAN OPERASI',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11200',
                'line' => 'DETAIL',
                'code_arus_kas' => '11200',
                'nama_arus_kas' => 'Penerimaan simpanan dari anggota dan koperasi lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11300',
                'line' => 'DETAIL',
                'code_arus_kas' => '11300',
                'nama_arus_kas' => 'Penyaluran pembiayaan kepada anggota dan koperasi lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11400',
                'line' => 'DETAIL',
                'code_arus_kas' => '11400',
                'nama_arus_kas' => 'Penerimaan dari pembiayaan kepada anggota dan koperasi lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11500',
                'line' => 'DETAIL',
                'code_arus_kas' => '11500',
                'nama_arus_kas' => 'Penerimaan pendapatan dari pembiayaan kepada anggota dan koperasi lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11600',
                'line' => 'DETAIL',
                'code_arus_kas' => '11600',
                'nama_arus_kas' => 'Pembayaran bagi hasil kepada anggota dan koperasi lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11700',
                'line' => 'DETAIL',
                'code_arus_kas' => '11700',
                'nama_arus_kas' => 'Penerimaan pembiayaan dari pihak lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11800',
                'line' => 'DETAIL',
                'code_arus_kas' => '11800',
                'nama_arus_kas' => 'Pembayaran pembiayaan dari pihak lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11900',
                'line' => 'DETAIL',
                'code_arus_kas' => '11900',
                'nama_arus_kas' => 'Pembayaran bagi hasil kepada pihak lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11910',
                'line' => 'DETAIL',
                'code_arus_kas' => '11910',
                'nama_arus_kas' => 'Biaya imbalan kerja',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-11920',
                'line' => 'DETAIL',
                'code_arus_kas' => '11920',
                'nama_arus_kas' => 'Biaya operasional',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 11000,
            ],
            [
                'gl_arus_kas' => '001-12000', // kegiatan investasi
                'line' => 'HEADING',
                'code_arus_kas' => '12000',
                'nama_arus_kas' => 'KEGIATAN INVESTASI',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000,
            ],
            [
                'gl_arus_kas' => '001-12200',
                'line' => 'DETAIL',
                'code_arus_kas' => '12200',
                'nama_arus_kas' => 'Penempatan Deposito Jangka Panjang',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000,
            ],
            [
                'gl_arus_kas' => '001-12300',
                'line' => 'DETAIL',
                'code_arus_kas' => '12300',
                'nama_arus_kas' => 'Penerimaan Bunga Deposito',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000,
            ],
            [
                'gl_arus_kas' => '001-12400',
                'line' => 'DETAIL',
                'code_arus_kas' => '12400',
                'nama_arus_kas' => 'Pencairan Deposito',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000,
            ],
            [
                'gl_arus_kas' => '001-12500',
                'line' => 'DETAIL',
                'code_arus_kas' => '12500',
                'nama_arus_kas' => 'Perolehan aset tetap',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000,
            ],
            [
                'gl_arus_kas' => '001-12600',
                'line' => 'DETAIL',
                'code_arus_kas' => '12600',
                'nama_arus_kas' => 'Pelepasan aset tetap',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000,
            ],
            [
                'gl_arus_kas' => '001-12700',
                'line' => 'DETAIL',
                'code_arus_kas' => '12700',
                'nama_arus_kas' => 'Perolehan aset tak berwujud',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000,
            ],
            [
                'gl_arus_kas' => '001-12800',
                'line' => 'DETAIL',
                'code_arus_kas' => '12800',
                'nama_arus_kas' => 'Pelepasan aset tak berwujud',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 12000, // end kegiatan investasi
            ],
            [
                'gl_arus_kas' => '001-13000', // kegiatan pendanaan
                'line' => 'HEADING',
                'code_arus_kas' => '13000',
                'nama_arus_kas' => 'KEGIATAAN PENDANAAN',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13200',
                'line' => 'SUB HEADING',
                'code_arus_kas' => '13200',
                'nama_arus_kas' => 'Penambahan modal :',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13300',
                'line' => 'DETAIL',
                'code_arus_kas' => '13300',
                'nama_arus_kas' => 'Simpanan pokok/modal tetap',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13400',
                'line' => 'DETAIL',
                'code_arus_kas' => '13400',
                'nama_arus_kas' => 'Simpanan wajib/modal tambahan',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13500',
                'line' => 'DETAIL',
                'code_arus_kas' => '13500',
                'nama_arus_kas' => 'Penempatan Dana Investasi',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13600',
                'line' => 'DETAIL',
                'code_arus_kas' => '13600',
                'nama_arus_kas' => 'Penerimaan pinjaman bank/lembaga keuangan lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13700',
                'line' => 'SUB HEADING',
                'code_arus_kas' => '13700',
                'nama_arus_kas' => 'Pengurangan modal :',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13800',
                'line' => 'DETAIL',
                'code_arus_kas' => '13800',
                'nama_arus_kas' => 'Simpanan pokok/modal tetap',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13900',
                'line' => 'DETAIL',
                'code_arus_kas' => '13900',
                'nama_arus_kas' => 'Simpanan wajib/modal tambahan',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13910',
                'line' => 'DETAIL',
                'code_arus_kas' => '13910',
                'nama_arus_kas' => 'Pencairan Dana Investasi',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13920',
                'line' => 'DETAIL',
                'code_arus_kas' => '13920',
                'nama_arus_kas' => 'Pembayaran pinjaman bank / lembaga keuangan lain',
                'unit' => '001',
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
            [
                'gl_arus_kas' => '001-13930',
                'line' => 'DETAIL',
                'code_arus_kas' => '13930',
                'nama_arus_kas' => 'Pembayaran Bagi Hasil anggota Dana Investasi',
                'unit' => '001', // ubah ke 1010
                'mut_debet' => 0,
                'mut_kredit' => 0,
                'saldo_awal' => 0,
                'saldo_akhir' => 0,
                'saldo_tahun' => 0,
                'group_heading' => 13000,
            ],
        ]);
    }
}
